#!/usr/bin/env bash
#
# This script will recover cephfs missing metada from data objects
# using a procedure described in:
#
# https://docs.ceph.com/en/quincy/cephfs/disaster-recovery-experts/#recovery-from-missing-metadata-objects
#

set -eo pipefail

#
# Globals
#
CEPHFS=
METADATAPOOL=
DATAPOOL=${CEPHFS_RECOVER_METADATA_DATAPOOL:-}
EXTRA_DATAPOOLS=
NRANKS=${CEPHFS_RECOVER_METADATA_NRANKS:-}
NWORKERS=${CEPHFS_RECOVER_METADATA_NWORKERS:16}
WAIT_SLEEP_INTERVAL=10
LOGDIR=recover_metadata_logs
: ${PROCESS_SCAN_LINK_LOG:=YES}
JOURNAL_RESET_COMPAT_FLAGS=
: ${FORCE_INIT:=}
: ${FORCE_CORRUPT:=}
: ${FORCE_POOL:=}
: ${DRY_RUN:=}

declare -A RECOVERY_STEPS=(
  [init]="INITIALIZING METADATA"
  [scan_extents]="SCANNING EXTENTS"
  [scan_inodes]="SCANNING INODES"
  [scan_links]="SCANNING LINKS"
  [cleanup]="CLEANUP"
  [end]="RECOVERY COMPLETE"
)
CURRENT_RECOVERY_STEP=""


#
# Functions
#
usage() {
    echo "$0 [options] <cephfs> [nranks [nworkers]]"
    echo
    echo "Options:"
    echo
    echo "  -d | --log-dir <dir>          directory to store logs (default: ${LOGDIR})"
    echo "  -h | --help                   show this help message and exit"
    echo "  -n | --dry-run                log recovery commands without executing them"
    echo "  -r | --ranks <N>              number of MDS ranks (get from FSMAp if not set)"
    echo "  -s | --wait-sleep <seconds>   wait sleep interval (default: ${WAIT_SLEEP_INTERVAL})"
    echo "  -w | --workers <N>            number of worker processes (default: ${NWORKERS})"
    echo "  -C | --force-corrupt          overrite apparently corrupt structures"
    echo "  -I | --force-init             write root inodes even if they exist"
    echo "  -P | --force-pool <datapool>  use data pool even if it is not in FSMap"
    echo
}

set_recovery_step() {
    local step="$1"

    if [ -n "${CURRENT_RECOVERY_STEP}" ]; then
        echo "${RECOVERY_STEPS[${CURRENT_RECOVERY_STEP}]} DONE" >&2
    fi

    CURRENT_RECOVERY_STEP="${step}"

    echo "${RECOVERY_STEPS[${step}]}" >&2
}

on_exit() {
    local rc=$?

    if [ $rc -ne 0 ] && [ -n "${CURRENT_RECOVERY_STEP}" ]; then
        echo "${RECOVERY_STEPS[${CURRENT_RECOVERY_STEP}]} FAILED" >&2
    fi

    exit $rc
}

check_deps() {
    if ! which jq >/dev/null 2>&1; then
	echo 'jq is not installed' >&2
	return 1
    fi
}

set_compat_flags() {
    if cephfs-journal-tool --help |
            grep -q 'reset .*--yes-i-really-really-mean-it'; then
        JOURNAL_RESET_COMPAT_FLAGS="--yes-i-really-really-mean-it"
    fi
}

prepare_log_dir() {
    test -n "${LOGDIR}"

    mkdir -p "${LOGDIR}"
    rm -f "${LOGDIR}"/*.log "${LOGDIR}"/*.dat

    echo "logs will be stored in ${LOGDIR}" >&2
}

get_nranks() {
    test -n "${NRANKS}" && test "${NRANKS}" -gt 0 && return

    NRANKS=$(ceph fs get ${CEPHFS} --format json |
		 jq '.mdsmap.max_mds')
    if [ -z "${NRANKS}" ] || [ "${NRANKS}" -le 0 ]; then
	echo "failed to get nranks for fs ${CEPHFS}" 2>&2
	return 1
    fi
}

get_metadatapool() {
    METADATAPOOLID=$(ceph fs get ${CEPHFS} --format json |
			 jq '.mdsmap.metadata_pool')
    if [ -z "${METADATAPOOLID}" ] || [ "${METADATAPOOLID}" -le 0 ]; then
	echo "failed to get metadatapoolid for fs ${CEPHFS}" 2>&2
	return 1
    fi

    METADATAPOOL=$(ceph df | awk '$2 == '${METADATAPOOLID}' {print $1}')
    if ! [ -n "${METADATAPOOL}" ]; then
	echo "failed to get datapool for datapoolid ${METADATAPOOLID}" 2>&2
	return 1
    fi
}

get_datapools() {
    local id datapool

    DATAPOOLIDS="$(ceph fs get ${CEPHFS} --format json | jq '.mdsmap.data_pools[]')"
    if [ -z "${DATAPOOLIDS}" ]; then
	echo "failed to get datapoolid for fs ${CEPHFS}: ${DATAPOOLIDS}" 2>&2
	return 1
    fi

    for id in ${DATAPOOLIDS}; do
	if [ ${id} -le 0 ]; then
	    echo "invalid datapool id for fs ${CEPHFS}: ${id}" 2>&2
	    return 1
	fi
	datapool=$(ceph df | awk '$2 == '${id}' {print $1}')
	if [ -z "${datapool}" ]; then
	    echo "failed to get datapool for datapoolid ${id}" 2>&2
	    return 1
	fi
	if [ -z "${DATAPOOL}" ]; then
	    DATAPOOL=${datapool}
	elif [ -z "${EXTRA_DATAPOOLS}" ]; then
	    EXTRA_DATAPOOLS=${datapool}
	else
	    EXTRA_DATAPOOLS="${EXTRA_DATAPOOLS} ${datapool}"
	fi
    done
}

run() {
    local name="$1"; shift
    local dry=

    test "${DRY_RUN}" = "YES" && dry="dry-"

    echo "${dry}running: $@" >&2

    echo $(date "+%F %T") "$@" >> "${LOGDIR}"/run.log

    test "${DRY_RUN}" = "YES" && return

    "$@" 2>&1 | tee -a "${LOGDIR}/${name}.log" >&2
}

cephfs_data_scan() {
    test -n "$1"
    local cmd="$1"; shift
    local datapools="${DATAPOOL}"
    local debug_mds=10

    test -n "$1"
    local worker="$1"; shift

    if [ "${cmd}" = "scan_extents" -a -n "${EXTRA_DATAPOOLS}" ]; then
	datapools="${datapools} ${EXTRA_DATAPOOLS}"
    fi

    if [ "${cmd}" = "cleanup" ]; then
	debug_mds=20
    fi

    echo "${cmd} ${worker} running" >&2

    run cephfs-data-scan."${cmd}"."${worker}" \
	cephfs-data-scan "${cmd}" --worker_n "${worker}" \
	--worker_m "${NWORKERS}" --filesystem "${CEPHFS}" \
	--debug-mds ${debug_mds} "$@" ${datapools}

    echo "${cmd} ${worker} complete" >&2
}

scan_extents() {
    test -n "$1"

    local worker="$1"; shift

    cephfs_data_scan scan_extents "${worker}" "$@" |
    awk -v f=${LOGDIR}/num_scan_extents.${worker}.dat \
	-v f0=${LOGDIR}/num_0_scan_extents.${worker}.dat \
    '
        BEGIN {
            n = n0 = 0
            print(n) > f; close(f)
            print(n0) > f0; close(0)
        }

        /handling object/ {
            n++
        }

        /handling object [0-9a0-f]*\.0$/ {
                n0++
        }

        n % 1000 == 0 {
            print(n) > f; close(f)
            print(n0) > f0; close(f0)
        }

        END {
            print(n) > f; close(f)
            print(n0) > f0; close(f0)
        }
    '
}

scan_inodes() {
    test -n "$1"

    local worker="$1"; shift

    cephfs_data_scan scan_inodes "${worker}" "$@" |
    awk -v f=${LOGDIR}/num_scan_inodes.${worker}.dat \
    '
        BEGIN {
            n = 0
            print(n) > f; close(f)
        }

        /handling object/ {
            n++
        }

        n % 1000 == 0 {
            print(n) > f; close(f)
        }

        END {
            print(n) > f; close(f)
        }
    '
}

scan_links() {
    run cephfs-data-scan.scan_links.0 \
	cephfs-data-scan scan_links --filesystem "${CEPHFS}" --debug-mds 10 "$@" |
    awk -v f=${LOGDIR}/num_scan_links.0.dat \
	-v d=${LOGDIR}/num_scan_links_dups.dat \
	-v r=${LOGDIR}/num_scan_links_rem_dups.dat \
	-v b=${LOGDIR}/num_scan_links_bad.dat \
	-v i=${LOGDIR}/num_scan_links_injected.dat \
    '
        BEGIN {
            n = 0
            print(n) > f; close(f)
        }

        /handling object/ {
            n++
        }

        n % 1000 == 0 {
            print(n) > f; close(f)
        }

        /processing .* dup_primaries/ {
            print(n) > f; close(f)
	    sub(/^.*datascan.scan_links: /, "")
	    print > d; close(d)
        }

	/removing dup dentries/ {
	    sub(/^.*datascan.scan_links: /, "")
	    print > r; close(r)
	}

	/processing .* bad_nlink_inos/ {
	    sub(/^.*datascan.scan_links: /, "")
	    print > b; close(b)
	}

	/processing .* injected_inos/ {
	    sub(/^.*datascan.scan_links: /, "")
	    print > i; close(i)
	}

        END {
            # ensure all files are created even if no matches
            printf("") > f; close(f)
            printf("") > d; close(d)
            printf("") > r; close(r)
            printf("") > b; close(b)
            printf("") > i; close(i)
        }
    '
}

cleanup() {
    test -n "$1"

    local worker="$1"; shift

    cephfs_data_scan cleanup "${worker}" "$@" |
    awk -v f=${LOGDIR}/num_cleanup."${worker}".dat \
	'
		BEGIN {
			n = 0
			print(n) > f; close(f)
		}

		/match|Non-zeroth object|skipping|read/ {
			n++
		}

		n % 1000 == 0 {
			print(n) > f; close(f)
		}

		END {
			print(n) > f; close(f)
		}
	'
}

wait_scan_extents_complete() {
    local objnum eobjnum sobjnum

    objnum=$(ceph df --format json |
                 jq -r '.pools[] | select(.name == "'${DATAPOOL}'").stats.objects')
    for pool in ${EXTRA_DATAPOOLS}; do
        eobjnum=$(ceph df --format json |
                      jq -r '.pools[] | select(.name == "'${pool}'").stats.objects')
	objnum=$((objnum + eobjnum))
    done

    if [ -z "${objnum}" ] || [ "${objnum}" -eq 0 ]; then
	wait
	return
    fi

    while sleep ${WAIT_SLEEP_INTERVAL}; do
	sobjnum=$(awk '{s += $1} END{print s}' "${LOGDIR}"/num_scan_extents.*.dat)
	test -n "${sobjnum}" || sobjnum=0
	echo "${sobjnum}/${objnum} objects ($((100 * sobjnum / objnum))%) processed" >&2

	jobs > "${LOGDIR}"/jobs
	test $(wc -l < "${LOGDIR}"/jobs) -eq 0 && break
    done
}

wait_scan_inodes_complete() {
    local objnum sobjnum

    objnum=$(awk '{s += $1} END{print s}' "${LOGDIR}"/num_0_scan_extents.*.dat)

    if [ -z "${objnum}" ] || [ "${objnum}" -eq 0 ]; then
	wait
	return
    fi

    while sleep ${WAIT_SLEEP_INTERVAL}; do
	sobjnum=$(awk '{s += $1} END{print s}' "${LOGDIR}"/num_scan_inodes.*.dat)
	test -n "${sobjnum}" || sobjnum=0
	echo "${sobjnum}/${objnum} objects ($((100 * sobjnum / objnum))%) processed" >&2

	jobs > "${LOGDIR}"/jobs
	test $(wc -l < "${LOGDIR}"/jobs) -eq 0 && break
    done
}

wait_scan_links_complete() {
    local objnum sobjnum
    local scan_done dup_done rem_dup_done bad_done
    local sleep_interval=${WAIT_SLEEP_INTERVAL}

    test -n "${PROCESS_SCAN_LINK_LOG}" &&
    objnum=$(ceph df --format json |
		 jq -r '.pools[] | select(.name == "'${METADATAPOOL}'").stats.objects')

    if [ -z "${objnum}" ] || [ "${objnum}" -eq 0 ]; then
	wait
	return
    fi

    # scan_links scans metadata objects twice
    objnum=$((objnum * 2))

    while sleep ${sleep_interval}; do
	if [ -n "${bad_done}" ]; then
	    test -f ${LOGDIR}/num_scan_links_injected.dat || continue
	    cat ${LOGDIR}/num_scan_links_injected.dat >&2
	    wait
	    break
	fi

	if [ -n "${rem_dup_done}" ]; then
	    if [ -f ${LOGDIR}/num_scan_links_bad.dat ]; then
		cat ${LOGDIR}/num_scan_links_bad.dat >&2
		bad_done=1
	    fi
	    continue
	fi

	if [ -n "${dup_done}" ]; then
	    if [ -f ${LOGDIR}/num_scan_links_rem_dups.dat ]; then
		cat ${LOGDIR}/num_scan_links_rem_dups.dat >&2
		rem_dup_done=1
	    fi
	    continue
	fi

	if [ -n "${scan_done}" ]; then
	    cat ${LOGDIR}/num_scan_links_dups.dat >&2
	    dup_done=1
	    continue
	fi

	sobjnum=$(awk '{s += $1} END{print s}' "${LOGDIR}"/num_scan_links.*.dat)
	test -n "${sobjnum}" || sobjnum=0
	echo "${sobjnum}/${objnum} objects ($((100 * sobjnum / objnum))%) processed" >&2

	if [ -f ${LOGDIR}/num_scan_links_dups.dat ]; then
	    scan_done=1
	    sleep_interval=1
	fi
    done
}

wait_cleanup_complete() {
    local objnum sobjnum

    # Ancillary data generated during recovery stored as xattrs in
    # zeroth object of each inode in the main data pool. So, cleanup
    # will traverse objects (all) in the main data pool only.
    objnum=$(ceph df --format json |
                 jq -r '.pools[] | select(.name == "'${DATAPOOL}'").stats.objects')

    if [ -z "${objnum}" ] || [ "${objnum}" -eq 0 ]; then
	wait
	return
    fi

    while sleep ${WAIT_SLEEP_INTERVAL}; do
	sobjnum=$(awk '{s += $1} END{print s}' "${LOGDIR}"/num_cleanup.*.dat)
	test -n "${sobjnum}" || sobjnum=0
	echo "${sobjnum}/${objnum} objects ($((100 * sobjnum / objnum))%) processed" >&2

	jobs > "${LOGDIR}"/jobs
	test $(wc -l < "${LOGDIR}"/jobs) -eq 0 && break
    done
}

#
# Main
#


OPTIONS=$(getopt -o d:hnr:s:w:CIP: --long log-dir:,help,dry-run,ranks:,wait-sleep:,workers:,force-corrupt,force-init,force-pool: -- "$@")

eval set -- "$OPTIONS"
while true; do
    case "$1" in
	-d|--log-dir)
	    if [ -d "$2" ]; then
		echo "Log directory $2 already exists" >&2
		exit 1
	    fi
            LOGDIR="$2"
	    shift 2
	    ;;
        -h|--help)
            usage
            exit 0
            ;;
	-n|--dry-run)
	    DRY_RUN=YES
	    shift
	    ;;
        -r|--ranks)
	    NRANKS="$2"
            shift 2
            ;;
        -s|--wait-sleep)
	    WAIT_SLEEP_INTERVAL="$2"
            shift 2
            ;;
        -w|--workers)
	    NWORKERS="$2"
            shift 2
            ;;
        -C|--force-corrupt)
	    FORCE_CORRUPT=YES
	    shift
            ;;
        -I|--force-init)
            FORCE_INIT=YES
            shift
            ;;
        -P|--force-pool)
	    DATAPOOL="$2"
            FORCE_POOL=YES
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Invalid option: $1" >&1
            usage >&2
            exit 1
            ;;
    esac
done

if [ -n "$1" ]; then
    CEPHFS=$1
    shift
fi
if [ -n "$1" ]; then
    NRANKS="$1"
    shift
fi
if [ -n "$1" ]; then
    NWORKERS="$1"
    shift
fi
if [ $? -ne 0 ]; then
    usage >&2
    exit 1
fi

if [ -z "${CEPHFS}" ]; then
    echo "cephfs name is required" 2>&2
    usage >&2
    exit 1
fi

if [ -n "${NRANKS}" ] && ! [ ${NRANKS} -ge 0 ]; then
    echo "invalid nranks: ${NRANKS}" 2>&2
    usage >&2
    exit 1
fi
if ! [ ${NWORKERS} -gt 0 -a ${NWORKERS} -le 512 ]; then
    echo "invalid nworkers: ${NWORKERS}" 2>&2
    usage >&2
    exit 1
fi

check_deps
set_compat_flags

get_nranks
get_metadatapool
get_datapools
prepare_log_dir

trap on_exit EXIT

set_recovery_step init

for rank in `seq 0 $((NRANKS - 1))`; do
    # try to recover whatever is possible from journal and reset it
    run journal_recover_dentries.${rank} \
	cephfs-journal-tool --rank=${CEPHFS}:${rank} event \
	recover_dentries summary || true
    run journal_reset.${rank}.log \
	cephfs-journal-tool --rank=${CEPHFS}:${rank} journal reset --force \
        ${JOURNAL_RESET_COMPAT_FLAGS}

    # reset session table
    run table_reset_session.${rank} \
	cephfs-table-tool ${CEPHFS}:${rank} reset session

    # reset SnapServer
    run table_reset_snap.${rank} \
	cephfs-table-tool ${CEPHFS}:${rank} reset snap

    # reset InoTable
    run table_reset_inode.${rank} \
	cephfs-table-tool ${CEPHFS}:${rank} reset inode

done

# Regenareate root inodes ("/" and MDS directory) if missing
extra_args=
if [ "${FORCE_INIT}" = "YES" ]; then
    echo "force-init enabled: will overrite root inodes" >&2
    extra_args="--force-init"
fi
run data_scan_init \
    cephfs-data-scan init --filesystem "${CEPHFS}" ${extra_args}

# List all inode objects (named as {inode}.{index}) in the data pool
# and accumulate collected inode information in {inode}.0 object
# attributes:
#   * the highest inode object index seen and its size ("scan_ceiling" xattr)
#   * the largest inode object seen ("scan_max_size")
#   * the highest inode object mtime seen ("scan_max_mtime" xattr)
#
# This information will be used on the next stepts to infer the object
# chunking size, the offset of the last object (chunk size * highest
# index seen), the actual size (offset of last object + size of
# highest ID seen), and the inode mtime
#
# NOTE: this logic doesn't take account of striping.
set_recovery_step scan_extents
extra_args=
if [ "${FORCE_POOL}" = "YES" ]; then
    extra_args="--force-pool"
fi
for worker in `seq 0 $((NWORKERS - 1))`; do
    scan_extents ${worker} ${extra_args} &
done
wait_scan_extents_complete

# Scan all {inode}.0 objects in the data pool, fetching previously
# accumulated data ("scan_ceiling", "scan_max_size", and
# "scan_max_mtime" xattrs), layout and backtrace data ("layout" and
# "parent" xattrs). Using this information rebuild (create or update)
# inode metadata in the metadata pool. Put strays and inodes without
# backtrace in lost+found.
set_recovery_step scan_inodes
extra_args=
if [ "${FORCE_CORRUPT}" = "YES" ]; then
    echo "force-corrupt enabled: will overrite corrupt structures" >&2
    extra_args="--force-corrupt"
fi
if [ "${FORCE_POOL}" = "YES" ]; then
    extra_args="--force-pool ${extra_args}"
fi
for worker in `seq 0 $((NWORKERS - 1))`; do
    scan_inodes ${worker} ${extra_args} &
done
wait_scan_inodes_complete

# Check inode linkages and fix found error. On the first step
# (SCAN_INOS) all inodes in metadata pool are scanned. If it is a
# dirfrag inode, its entries are read to detect dups. If it is a link
# inode, the ref count is increased for the inode it reffers to.  On
# the second step (CHECK_LINK) it resolves found dups and other
# inconsitencies.
set_recovery_step scan_links
scan_links &
wait_scan_links_complete

# Delete ancillary data generated during recovery (xattrs).
set_recovery_step cleanup
for worker in `seq 0 $((NWORKERS - 1))`; do
    cleanup ${worker} &
done
wait_cleanup_complete

set_recovery_step end
