name: Build Binary Job

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
        default: binary-dist

env:
  GIT_DEPTH: 0

jobs:
  build_binary:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    steps:
      - name: Setup CentOS repositories
        run: |
          cd /etc/yum.repos.d/
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

      # Git must be installed and configured before checkout
      # setuptools-scm (used in copilot/pyproject.toml) needs git to read tags during build
      # If git isn't properly configured, setuptools-scm falls back to version 0.0.0
      - name: Install git and configure safe directory
        run: |
          yum install -y git
          git config --global --add safe.directory .

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}

      - name: Install remaining dependencies
        run: |
          yum install -y curl
          curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=/usr/bin UV_DISABLE_UPDATE=1 UV_NO_MODIFY_PATH=1 /bin/sh

      - name: Build binary
        run: ./build.sh

      - name: Test binary
        run: |
          ./dist/otto --version
          ./dist/otto --help
          VERSION=$(./dist/otto --version | grep -oP 'v\d+\.\d+\.\d+')
          if [ "$VERSION" = "v0.0.0" ]; then
            echo "Error: Version is v0.0.0, git tags not properly detected"
            exit 1
          fi

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist/
          retention-days: 1
