name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  GIT_DEPTH: 0

jobs:
  build_binary:
    uses: ./.github/workflows/build-binary-job.yml
    with:
      artifact_name: binary

  build_rpm:
    uses: ./.github/workflows/build-rpm-job.yml
    with:
      artifact_name: rpm
      run_tests: false

  create_release:
    runs-on: ubuntu-latest
    needs: [build_binary, build_rpm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release if it doesn't exist
        run: |
          if ! gh release view "${{ github.ref_name }}" > /dev/null 2>&1; then
            gh release create "${{ github.ref_name }}" --title "Release ${{ github.ref_name }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload to release
        run: |
         gh release upload ${{ github.ref_name }} \
            binary/otto \
            rpm/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
