name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  GIT_DEPTH: 0

jobs:
  build_binary:
    uses: ./.github/workflows/build-binary-job.yml
    with:
      artifact_name: binary

  build_rpm:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    steps:
      - name: Install git 
        run: |
          dnf install -y git
          git config --global --add safe.directory .

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}

      - name: Install dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --enable crb
          dnf install -y git rpm-build rpmdevtools python3-devel
          curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=/usr/bin UV_DISABLE_UPDATE=1 UV_NO_MODIFY_PATH=1 /bin/sh

      - name: Build RPM
        run: ./build_rpm.sh

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm
          path: "*.rpm"
          retention-days: 1

  create_release:
    runs-on: ubuntu-latest
    needs: [build_binary, build_rpm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release if it doesn't exist
        run: |
          if ! gh release view "${{ github.ref_name }}" > /dev/null 2>&1; then
            gh release create "${{ github.ref_name }}" --title "Release ${{ github.ref_name }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload to release
        run: |
         gh release upload ${{ github.ref_name }} \
            binary/clyq \
            rpm/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
